# Generated by Django 4.2.13 on 2026-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskwatcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
