# Generated by Django 4.2.13 on 2026-05-05 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user.registered", "User registered"),
                            ("user.login", "User logged in"),
                            ("user.logout", "User logged out"),
                            ("user.updated", "User profile updated"),
                            ("task.created", "Task created"),
                            ("task.updated", "Task updated"),
                            ("task.deleted", "Task deleted"),
                            ("task.assigned", "Task assigned"),
                            ("task.status_changed", "Task status changed"),
                            ("notification.sent", "Notification sent"),
                            ("notification.read", "Notification marked read"),
                            ("system.error", "System error"),
                            ("celery.task_failed", "Celery task failed"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, help_text="e.g. Task, Notification", max_length=60
                    ),
                ),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="log_user_time_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="log_action_time_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"], name="log_resource_idx"
                    ),
                ],
            },
        ),
    ]
