# Generated by Django 4.2.13 on 2026-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_notification_channel_taskevent_notificationdelivery_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
